arch = [
  "base",
  "base-devel",
  "chezmoi",
  "efibootmgr",
  "git",
  "grub",
  "linux",
  "linux-firmware",
  "linux-headers",
  "metapac",
  "networkmanager",
  "sof-firmware",
  "yay",
  "yay-debug",
  "nano",
  "vim",
  "bluez",
  "bluez-utils",
  "cups",
  "cups-pk-helper",
  "gst-plugin-pipewire",
  "intel-ucode",
  "libpulse",
  "pacdef-bin",
  "pipewire",
  "pipewire-alsa",
  "pipewire-jack",
  "pipewire-pulse",
  "sudo",
  "system-config-printer",
  "wireplumber",
  "wpa_supplicant",
  "zram-generator",
]