arch = [
  "aconfmgr-git",
  "base",
  "base-devel",
  "btop",
  "chezmoi",
  "dunst",
  "efibootmgr",
  "fastfetch",
  "firefox",
  "git",
  "google-chrome",
  "grim",
  "grub",
  "htop",
  "hyprland",
  "hyprlauncher",
  "kitty",
  "lazygit",
  "libva",
  "linux",
  "linux-firmware",
  "linux-headers",
  "metapac",
  "nano",
  "nemo",
  "networkmanager",
  "nvidia-open-dkms",
  "nvidia-settings",
  "nvidia-utils",
  "pacdef-bin",
  "qt5-wayland",
  "qt6-wayland",
  "slurp",
  "sof-firmware",
  "swww",
  "telegram-desktop",
  "throne-bin",
  "vim",
  "visual-studio-code-bin",
  "wl-clipboard",
  "xdg-desktop-portal-hyprland",
  "yay",
  "yay-debug",
]
