[arch]
packages = [
    "caelestia-cli",
    "quickshell-git",
    "ddcutil",
    "brightnessctl",
    "app2unit",
    "libcava",
    "lm_sensors",
    "aubio",
    "libpipewire",
    "glibc",
    "qt6-declarative",
    "gcc-libs",
    "ttf-material-icons-git",
    # "caskaydia-cove-nerd",
    "swappy",
    "libqalculate",
    "bash",
    "qt6-base",
    "qt6-declarative"
]