[arch]
packages = [
  # Text editors
  "nano",
  "vim",

  # Cloud
  "yandex-disk",

  # Fun
  "cmatrix",
  "cava",

  "btop",
  "fastfetch",
  "htop",
  "bat",
  "eza",

  "lazygit",
  "lazydocker"
]