[arch]
packages = [
  # Text editors
  "nano",
  "vim",
  "neovim",

  # LazyVim first important plugins
  "tree-sitter-cli",
  "ripgrep",
  "fd",

  # Cloud
  "yandex-disk",

  # Fun
  "cmatrix",
  "cava",

  "btop",
  "fastfetch",
  "htop",
  "bat",
  "eza",

  "lazygit",
  "lazydocker"
]