[arch]
packages = [
  # Python
  "uv",

  # C++
  "gcc",
  "gdb",
  "valgrind",
  "clang",
  "cmake",

  # Node js
  "mise"
]

[mise]
packages = [{name = "node", options = { version = "lts" }}]

# [npm]
# packages = [
#   "yarn",
# ]