[arch]
packages = [
  # Python
  "uv",

  # C++
  "gcc",
  "gdb",
  # "codelldb",
  "lldb",
  "valgrind",
  "clang",
  "cmake",

  # Node js
  "mise",

  # Docker
  "docker",
  "docker-compose",

  # Remote access
  "openssh",
  "tailscale",
  "firewalld"
]

[mise]
packages = [{name = "node", options = { version = "lts" }}]

# [npm]
# packages = [
#   "yarn",
# ]