[arch]
packages = [
    "steam",
    "lutris",
    "wine-staging",
    "winetricks",
    "gamemode",
    "lib32-gamemode",
    "mangohud",
    "lib32-mangohud",
    "jdk17-openjdk",
    "jdk21-openjdk",
    "jdk-openjdk"
]