[arch]
packages = [
    "steam",
    "lutris",
    "wine-staging",
    "winetricks",
    "gamemode",
    "lib32-gamemode",
    "mangohud",
    "lib32-mangohud",
    # "jre17-openjdk",
    "jdk17-openjdk"
]