arch = {packages = [
  "firefox",
  "google-chrome",
  "kitty",

  "nemo",
  "file-roller",
  "nemo-fileroller",

  "telegram-desktop",
  "visual-studio-code-bin",
  "wl-clipboard",
  "throne-bin",
  "obsidian"
]}