arch = [
  "firefox",
  "google-chrome",
  "kitty",

  "nemo",
  "file-roller",
  "nemo-fileroller",

  # "dolphin",
  # "thunar",
  # "thunar-archive-plugin",
  # "thunar-media-tags-plugin",
  # "tumbler",

  "telegram-desktop",
  "visual-studio-code-bin",
  "wl-clipboard",
  "throne-bin",
  "obsidian"
]