enabled_backends = ["arch"]

hostname_groups_enabled = true

[arch]
package_manager = "yay"

[hostname_groups]
"declarch" = ["base", "fonts", "cli", "gui", "hyprland", "nvidia", "virtualization"]
"declarch-laptop"  = ["base", "fonts", "cli", "gui", "hyprland"]