enabled_backends = ["arch", "mise", "npm", "yarn"]

hostname_groups_enabled = true

[arch]
package_manager = "yay"

[hostname_groups]
"declarch" = ["base", "fonts", "cli", "gui", "hyprland", "nvidia", "dev", "celestia-shell", "remote", "virtualization", "themes"]
"declarch-laptop"  = ["base", "fonts", "cli", "gui", "hyprland", "intel-graphics", "dev", "celestia-shell", "remote", "themes", "gaming", "gamedev"]